# Generated by Django 4.1.10 on 2023-10-02 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='time',
            field=models.TimeField(default=datetime.time(18, 40, 12, 791422)),
        ),
    ]
