# Generated by Django 4.1.10 on 2023-10-02 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_alter_seat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='time',
            field=models.TimeField(default=datetime.time(18, 41, 43, 647729)),
        ),
    ]
